# Generated by Django 3.2.6 on 2021-08-31 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0006_alter_fakeuser_password'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fakeuser.fakeuser'),
            preserve_default=False,
        ),
    ]
