# Generated by Django 3.2.6 on 2021-11-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='decription',
            new_name='description',
        ),
    ]
