# Generated by Django 3.2.6 on 2022-01-11 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220110_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img',
        ),
    ]
