# Generated by Django 3.2.6 on 2022-01-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_images_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='img',
            field=models.ImageField(null=True, upload_to='store/'),
        ),
    ]
