# Generated by Django 3.2.6 on 2022-01-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_images_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img',
        ),
    ]
