# Generated by Django 3.2.6 on 2021-09-17 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo de la API')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ApiDocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=250, verbose_name='Nombre de la API')),
                ('description', models.TextField(verbose_name='Describe lo que hace esta API')),
                ('api_direction', models.TextField(verbose_name='Direccion URL de la API')),
                ('api_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='docs.apidoc')),
            ],
        ),
    ]
