# Generated by Django 3.2.6 on 2021-09-17 23:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidocsection',
            name='description',
        ),
        migrations.AddField(
            model_name='apidoc',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripcion de la API'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apidocsection',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Describe algun punto iportante de la API'),
        ),
        migrations.AlterField(
            model_name='apidocsection',
            name='api_direction',
            field=ckeditor.fields.RichTextField(verbose_name='Direccion URL de la API'),
        ),
    ]
