# Generated by Django 3.2.6 on 2021-09-18 00:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210917_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidocsection',
            name='api_response',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Respuesta de la API'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apidocsection',
            name='api_direction',
            field=models.CharField(max_length=255, verbose_name='URL de la API'),
        ),
    ]
