# Generated by Django 3.2.6 on 2021-09-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20210917_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidoc',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
