# Generated by Django 3.2.6 on 2021-09-18 00:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_apidoc_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidocsection',
            name='api_direction',
        ),
        migrations.AddField(
            model_name='apidocsection',
            name='api_request',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Peticion a la API'),
            preserve_default=False,
        ),
    ]
