# Generated by Django 3.2.6 on 2021-11-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210917_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidoc',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
