# Generated by Django 3.2.6 on 2022-01-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_apidoc_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidoc',
            name='img',
        ),
        migrations.AddField(
            model_name='apidoc',
            name='imgURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
