# Generated by Django 3.2.6 on 2021-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('password', models.CharField(default='7779f417', max_length=8)),
            ],
        ),
    ]
