# Generated by Django 3.2.6 on 2021-08-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0004_auto_20210830_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faketoken',
            old_name='token',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='2a05712e', max_length=8),
        ),
    ]
