# Generated by Django 3.2.6 on 2021-08-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0005_auto_20210831_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='2aa49e64', max_length=8),
        ),
    ]
