# Generated by Django 3.2.6 on 2021-08-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0006_alter_fakeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='169376c1', max_length=8),
        ),
    ]
