# Generated by Django 3.2.6 on 2021-09-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0007_alter_fakeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='89041296', max_length=8),
        ),
    ]
