# Generated by Django 3.2.6 on 2021-09-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0009_alter_fakeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='ad24fcf6', max_length=8),
        ),
    ]
