# Generated by Django 3.2.6 on 2021-09-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0010_alter_fakeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='5aa04cc6', max_length=8),
        ),
    ]
