# Generated by Django 3.2.6 on 2021-09-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0014_alter_fakeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='d51a20c3', max_length=8),
        ),
    ]
