# Generated by Django 3.2.6 on 2021-11-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0018_alter_fakeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='8576bbc3', max_length=8),
        ),
    ]
