# Generated by Django 3.2.6 on 2022-01-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0021_alter_fakeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='6ed96e99', max_length=8),
        ),
    ]
