# Generated by Django 3.2.6 on 2022-03-29 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0025_auto_20220328_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('street_number', models.CharField(blank=True, max_length=15)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='name',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='gender_abbrev',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fakeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='9967cb7b', max_length=8),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='location',
            name='personal_inf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='fakeuser.personalinformation'),
        ),
    ]
