# Generated by Django 3.2.6 on 2022-03-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeuser', '0026_auto_20220328_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(default='08557f83', max_length=8),
        ),
    ]
